AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - .vendor/**/*
    - pkg/**/*
    - test/stack_overflow_test.rb
    - tmp/**/*

# This should probably be updated
Gemspec/RequireMFA:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/UnusedMethodArgument:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - test/**/*
    - Rakefile

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 45
  Exclude:
    - test/**/*

Metrics/ParameterLists:
  Max: 8
  MaxOptionalParameters: 8

Metrics/PerceivedComplexity:
  Max: 20

Security/Eval:
  Exclude:
    - bin/*

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AccessorGrouping:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/tree_sitter/extconf.rb
Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# `unless` is cool and all, but I'd rather not. Less confusion.
Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false
