name: CI

on:
  pull_request:
  push:
    branches:
      - "master"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2, 3.3]
        platform:
          - { os: ubuntu, target: linux-x64 }
    runs-on: ${{ matrix.platform.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just,typos
      - name: typos
        run: just typos
      - name: setup
        run: just setup
      - name: lint
        run: just lint
      - name: test
        run: just test
      - name: doc
        run: just doc
      - name: package gem
        run: just gem
